### ISSUE TITLE
tag a first release

### ISSUE THREAD

**Issue by tbeason** [JuliaStats/HiddenMarkovModels.jl#6]
Thanks for giving this package some love. It would help tremendously if you were to register a first release in the general registry!

**Comment by gdalle** [comment]
I would like to improve the docs a bit first, have you tried it yourself? What would you add before tagging v0.1?

**Comment by tbeason** [comment]
I am estimating pretty simple 2-state HMMs and then extracting the Viterbi paths. It seems like the functionality is there at this point. I see you have some things marked as to-do, like benchmarks, but I can tell you this is already plenty fast!

One thing that might be missing is a helper for estimating multiple times from different starting points, for robustness against local maxima. This is easy enough to do on my own though.

**Comment by gdalle** [comment]
> I see you have some things marked as to-do, like benchmarks, but I can tell you this is already plenty fast!

I honestly think it is about as fast as it can get while staying modular. I like the idea of just plugging in LogarithmicNumbers to ensure numerical stability, but it comes at the cost of performance. Without LogarithmicNumbers I should be slightly faster than HMMBase, but with them I'm falling behind. At least that's what preliminary benchmarks would suggest. I still hope to blow Python alternatives out of the water though.

> One thing that might be missing is a helper for estimating multiple times from different starting points, for robustness against local maxima. This is easy enough to do on my own though.

You mean passing a list of `hmm_init` instead of a single one? Sure, I could add that, but it seems like generating a "diverse" set of `hmm_init` would best be left to the user anyway, so I don't think it would save much work.

**Comment by gdalle** [comment]
I'll tag a release before the week-end is over

**Comment by gdalle** [comment]
@tbeason https://github.com/JuliaRegistries/General/pull/85313
